### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

POST http://localhost:8081/api/order
Content-Type: application/json

{
  "orderItemDtoList": [
    {
      "skuCode": "iPhone-14",
      "price": 1300,
      "quantity": 1
    }
  ]
}