
POST http://localhost:8083/api/inventory
Content-Type: application/json

{
"skuCode" : "iPhone-17",
"quantity": 100
}

### Get product by skucode

GET http://localhost:8083/api/inventory?skuCode=iPhone-13
